/-
Copyright (c) 2024 Florent Schaffhauser. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Florent Schaffhauser, Artie Khovanov
-/
import Mathlib.Order.Zorn
import RealClosedField.Algebra.Order.Ring.Ordering.Basic

/-!

Let `R` be a commutative ring, and let `P` be a preordering on `R`.

## Main results

* `Subsemiring.IsPreordering.exists_le`: if `a ∉ P`, then `P` extends to a preordering
containing either `a` or `-a`.
* `Subsemiring.IsPreordering.exists_le_isOrdering`: `P` extends to an ordering.
* `Subsemiring.maximal_isPreordering_iff_maximal_isOrdering`:
an ordering is maximal as an ordering if and only if it is maximal as a preordering.
* `Subsemiring.maximal_isPreordering_iff_isOrdering`: over a field,
orderings are precisely maximal preorderings.

## References

- *An introduction to real algebra*, by T.Y. Lam. Rocky Mountain J. Math. 14(4): 767-814 (1984).
[lam_1984](https://doi.org/10.1216/RMJ-1984-14-4-767)

-/

-- TODO : replace `aesop` with `membership`

variable {R : Type*} [CommRing R]

namespace Subsemiring.IsPreordering

variable {P : Subsemiring R} (a : R)

/-
### Sufficient conditions for adjoining an element to a preordering
-/

variable {a} in
theorem closure_insert (hP : P.IsPreordering) (hx : -1 ∉ closure (insert a P)) :
    (closure (insert a P)).IsPreordering := hP.of_le (fun _ ↦ by aesop) hx

variable {a} in
theorem mem_closure_insert (hP : P.IsPreordering) {x} :
    x ∈ closure (insert a P) ↔ ∃ y ∈ P, ∃ z ∈ P, x = y + a * z where
  mp hx := by
    induction hx using Subsemiring.closure_induction with
    | mem x hx => cases hx
                  · exact ⟨0, by aesop, 1, by aesop, by simp_all⟩
                  · exact ⟨x, ‹_›, 0, by aesop, by simp⟩
    | zero => exact ⟨0, by aesop, 0, by aesop, by simp⟩
    | one => exact ⟨1, by aesop, 0, by aesop, by simp⟩
    | add _ _ _ _ ha hb =>
      rcases ha, hb with ⟨⟨x₁, hx₁, y₁, hy₁, rfl⟩, ⟨x₂, hx₂, y₂, hy₂, rfl⟩⟩
      exact ⟨x₁ + x₂, by aesop, y₁ + y₂, by aesop, by grind⟩
    | mul _ _ _ _ ha hb =>
      rcases ha, hb with ⟨⟨x₁, hx₁, y₁, hy₁, rfl⟩, ⟨x₂, hx₂, y₂, hy₂, rfl⟩⟩
      exact ⟨x₁ * x₂ + (a * a) * (y₁ * y₂), by aesop, x₁ * y₂ + y₁ * x₂, by aesop,
        by grind⟩
  mpr := by aesop

theorem neg_one_notMem_closure_insert (hP : P.IsPreordering)
    (h : ∀ x y, x ∈ P → y ∈ P → x + (1 + y) * a + 1 ≠ 0) :
    -1 ∉ closure (insert a P) := fun _ ↦ by
  rcases hP.mem_closure_insert.mp
      (show -1 * (1 + a) ∈ closure (insert a P) by aesop (erase simp neg_mul))
    with ⟨x, hx, y, hy, eqn⟩
  exact h _ _ hx hy (by grind)

theorem neg_one_notMem_closure_insert_or_of_neg_mul_mem (hP : P.IsPreordering)
    {x y : R} (h : -(x * y) ∈ P) :
    -1 ∉ closure (insert x P) ∨ -1 ∉ closure (insert y P) := by
  rw [hP.mem_closure_insert]
  by_contra
  apply hP.neg_one_notMem
  rcases hP.mem_closure_insert.mp (show -1 ∈ closure (insert x P) by aesop)
    with ⟨s₁, hs₁, s₂, hs₂, eqx⟩
  rcases hP.mem_closure_insert.mp (show -1 ∈ closure (insert y P) by aesop)
    with ⟨t₁, ht₁, t₂, ht₂, eqy⟩
  suffices (-(x * y)) * s₂ * t₂ + s₁ + t₁ + (s₁ * t₁) ∈ P by grind
  aesop (config := { enableSimp := false })

/--
If `F` is a field, `P` is a preordering on `F`, and `a` is an element of `P` such that `-a ∉ P`,
then `-1` is not in the semiring generated by `P` and `a`.
-/
theorem neg_one_notMem_closure_insert_of_neg_notMem
    {F : Type*} [Field F] {P : Subsemiring F} (hP : P.IsPreordering) {a : F} (ha : -a ∉ P) :
    -1 ∉ Subsemiring.closure (insert a P) := by
  rw [hP.mem_closure_insert]
  rintro ⟨x, hx, y, hy, eqn⟩
  apply ha
  suffices x * y⁻¹ + y⁻¹ ∈ P by grind [hP.neg_one_notMem]
  aesop (add unsafe inv_mem)

theorem exists_le_and_mem_or_mem (hP : P.IsPreordering) (x y : R) (h : -(x * y) ∈ P) :
    ∃ Q ≥ P, Q.IsPreordering ∧ (x ∈ Q ∨ y ∈ Q) := by
  rcases hP.neg_one_notMem_closure_insert_or_of_neg_mul_mem h with h | h <;>
    exact ⟨_, fun _ ↦ by aesop, hP.closure_insert h, by aesop⟩

/- A maximal preordering on `R` is an ordering. -/
theorem _root_.Subsemiring.IsOrdering.of_maximal_isPreordering
    (max : Maximal IsPreordering P) : P.IsOrdering :=
  max.prop.isOrdering_iff.mpr <| fun a b h => by
  rcases max.prop.exists_le_and_mem_or_mem _ _ h with ⟨O', hO'₁, hO'₂, hO'₃⟩
  aesop (add safe forward (max.le_of_ge hO'₂ hO'₁))

/- Every preordering on `R` extends to an ordering. -/
theorem exists_le_isOrdering (hP : P.IsPreordering) :
    ∃ O ≥ P, O.IsOrdering :=
  have ⟨_, _, hO⟩ : ∃ O, P ≤ O ∧ Maximal IsPreordering O := by
    refine zorn_le_nonempty₀ {P : Subsemiring R | IsPreordering P} ?_ P (by simpa)
    exact fun S hS hc Q hQ ↦
      ⟨_, IsPreordering.sSup (Set.nonempty_of_mem hQ) hc.directedOn hS, fun _ h ↦ le_sSup h⟩
  ⟨_, ‹_›, .of_maximal_isPreordering hO⟩

theorem exists_le_isOrdering_and_mem
    {P : Subsemiring R} (hP : P.IsPreordering) {a : R} (h : -1 ∉ closure (insert a P)) :
    ∃ O ≥ P, O.IsOrdering ∧ a ∈ O := by
  rcases (hP.closure_insert h).exists_le_isOrdering with ⟨_, _, hO⟩
  exact ⟨_, fun _ ↦ by aesop, hO, by aesop⟩

theorem exists_le_isOrdering_and_mem_or_neg_mem (hP : P.IsPreordering) :
    ∃ Q ≥ P, Q.IsOrdering ∧ (a ∈ Q ∨ -a ∈ Q) := by
  rcases hP.exists_le_and_mem_or_mem a (-a) (by simp [hP]) with ⟨_, _, hP', _⟩
  rcases hP'.exists_le_isOrdering with ⟨_, _, hO⟩
  exact ⟨_, by grind, hO, by aesop⟩

theorem exists_lt_isOrdering (hP : P.IsPreordering) (hp : a ∉ P) (hn : -a ∉ P) :
    ∃ Q > P, Q.IsOrdering := by
  rcases hP.exists_le_isOrdering_and_mem_or_neg_mem a with ⟨_, _, hQ, _ | _⟩ <;>
    exact ⟨_, by grind [lt_of_le_of_ne], hQ⟩

end IsPreordering

/- A maximal ordering on `R` is precisely a maixmal preordering on `R`. -/
theorem maximal_isOrdering_iff_maximal_isPreordering {O : Subsemiring R} :
    Maximal IsOrdering O ↔ Maximal IsPreordering O where
  mp hO :=
    ⟨hO.prop.isPreordering, fun _ hP _ ↦ by
      rcases hP.exists_le_isOrdering with ⟨O', hO', hO'₂⟩
      simpa [Maximal.eq_of_ge hO hO'₂ (by order)] using hO'⟩
  mpr hO := .mono hO (fun _ hO ↦ hO.isPreordering) (.of_maximal_isPreordering hO)

/- A preordering on a field `F` is maximal iff it is an ordering. -/
theorem maximal_isPreordering_iff_isOrdering {F : Type*} [Field F] {O : Subsemiring F} :
    Maximal IsPreordering O ↔ O.IsOrdering where
  mp := .of_maximal_isPreordering
  mpr hO := ⟨hO.isPreordering, fun _ hO' ↦
    (hO.isSpanning.maximal_isPointed hO.isPreordering.isPointed).le_of_ge hO'.isPointed⟩
